# Generated by Django 4.0.3 on 2022-03-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('penulis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, null=True)),
                ('isi', models.TextField()),
                ('kategori', models.CharField(blank=True, choices=[('KESEHATAN', 'Kesehatan'), ('KEPEGAWAIAN', 'Kepegawaian')], max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('penulis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penulis.penulis')),
            ],
        ),
    ]
