# Generated by Django 4.0.3 on 2022-04-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_artikel_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='status',
            field=models.CharField(choices=[('unpublished', 'unpublised'), ('published', 'published')], default='unpublished', max_length=200),
        ),
    ]
