# Generated by Django 4.0.3 on 2022-05-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penulis', '0003_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='spesialist',
            name='jadwal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='spesialist',
            name='profile_pic',
            field=models.ImageField(default='profile1.png', null=True, upload_to=''),
        ),
    ]
