# Generated by Django 4.0.3 on 2022-07-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penulis', '0004_spesialist_jadwal_spesialist_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senin', models.TextField()),
                ('selasa', models.TextField()),
                ('rabu', models.TextField()),
                ('kamis', models.TextField()),
                ('jumat', models.TextField()),
                ('sabtu', models.TextField()),
                ('dokter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penulis.spesialist')),
            ],
        ),
    ]
