# Generated by Django 4.0.3 on 2022-07-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penulis', '0005_jadwaldokter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesialist',
            name='spesialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penulis.departement'),
        ),
    ]
