# Generated by Django 4.0.3 on 2022-08-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penulis', '0006_alter_spesialist_spesialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwaldokter',
            name='jumat',
            field=models.TextField(choices=[('08:00 - 11:45', '08:00 - 11:45'), ('Kosong', 'Kosong'), ('Cuti', 'Cuti')]),
        ),
        migrations.AlterField(
            model_name='jadwaldokter',
            name='kamis',
            field=models.TextField(choices=[('08:30 - 14:15', '08:30 - 14:15'), ('Kosong', 'Kosong'), ('Cuti', 'Cuti')]),
        ),
        migrations.AlterField(
            model_name='jadwaldokter',
            name='rabu',
            field=models.TextField(choices=[('08:30 - 14:15', '08:30 - 14:15'), ('Kosong', 'Kosong'), ('Cuti', 'Cuti')]),
        ),
        migrations.AlterField(
            model_name='jadwaldokter',
            name='sabtu',
            field=models.TextField(choices=[('08:30 - 14:15', '08:30 - 14:15'), ('Kosong', 'Kosong'), ('Cuti', 'Cuti')]),
        ),
        migrations.AlterField(
            model_name='jadwaldokter',
            name='selasa',
            field=models.TextField(choices=[('08:30 - 14:15', '08:30 - 14:15'), ('Kosong', 'Kosong'), ('Cuti', 'Cuti')]),
        ),
        migrations.AlterField(
            model_name='jadwaldokter',
            name='senin',
            field=models.TextField(choices=[('08:30 - 14:15', '08:30 - 14:15'), ('Kosong', 'Kosong'), ('Cuti', 'Cuti')]),
        ),
    ]
