# Generated by Django 4.0.3 on 2022-08-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penulis', '0007_alter_jadwaldokter_jumat_alter_jadwaldokter_kamis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
